### Variables 
@url = http://localhost:3000/api

### GET links
GET {{url}}/links

### POST links
POST {{url}}/links HTTP/1.1
Content-Type: application/json

{
  "url_original": "https://example.com2",
  "legenda": "Legenda do meu Link"
}